### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by emilyjanedennis** [bonsai-rx/sleap#19]
for now, for single instance models, only pb files from sleap 1.2.9 work, not the most recent versions. Would be great to have this in the documentation (I learned the hard way by finding an issue after my training failed)

**Comment by banchan86** [comment]
thanks emily for bringing this to our attention!

**Comment by glopesdev** [comment]
@emilyjanedennis @banchan86 this has been fixed in #21 and will be released soon together with updated documentation.
